/* Este archivo contiene los comandos para borrar el tablespace, usuarios y objetos creados en los otros archivos */

DROP TABLESPACE SOLUCIONES_MOVILES_INDEX INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE SOLUCIONES_MOVILES_DATOS INCLUDING CONTENTS AND DATAFILES; 

DROP USER ABD CASCADE; 
DROP USER ADMINISTRADOR1 CASCADE;
DROP USER ORGANIZADOR1 CASCADE;